version: '3.8'

services:

  nginx:
    image: nginx:alpine
    container_name: wifi_nginx
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./backend:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  app:
    build: .
    container_name: wifi_app
    restart: always
    volumes:
      - ./backend:/var/www/html:cached
      - ./php/www.conf:/usr/local/etc/php-fpm.d/www.conf
    depends_on:
      - db
      - freeradius

  db:
    image: mysql:8.0
    container_name: wifi_db
    restart: always
    environment:
      MYSQL_DATABASE: wifi_platform
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  freeradius:
    image: freeradius/freeradius-server:latest  # <-- CORREGIDO
    container_name: wifi_freeradius
    restart: always
    ports:
      - "1812:1812/udp"
      - "1813:1813/udp"
    volumes:
      - ./freeradius/users:/etc/raddb/users
      - ./freeradius/clients.conf:/etc/raddb/clients.conf
    depends_on:
      - db

volumes:
  db_data:
